### PR TITLE
cache element Y co-ordinate

### PR DESCRIPTION
**Pull request by sarbbottam**
Please close the PR if I sound inappropriate.

### CODE REVIEW

**Comment by kevva** [comment]
Thanks :).

**Comment by sarbbottam** [comment]
This the first time I have seem commits in PR (with changes on top of it) merged but PR closed :).

Interested to know what has been your workflow.

Was it?
- fetch the PR as a local branch
- make changes on the PR
- amend it to last commit
- rebase it with master
- and push the master

**Comment by kevva** [comment]
That's exactly what I did :). If you aren't using [`hub`](https://github.com/github/hub) or something else I have a good alias for checking out PRs https://github.com/kevva/dot-files/blob/master/git/gitinclude#L64-L65.

I also renamed your commit message and added `Fixes #1` to close the PR from the commit.

**Comment by sarbbottam** [comment]
> something else I have a good alias for checking out PRs

I have something almost similar - https://github.com/sarbbottam/conf-files/blob/master/common-shell-confs/functions#L23-L35

**Pull request closed without merging**
